/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;

import cinema.models.Movie;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ivan
 */
public class AddMovieUI extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMovieUI.class.getName());

	/**
	 * Creates new form AddMovieUI
	 */
	
	private ManagerUI parent;
	public AddMovieUI(ManagerUI parent) {
		this.parent = parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        ratingField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        genreField = new javax.swing.JTextField();
        addImagebutton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        imageField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        imagePreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Title");

        jLabel2.setText("Genre");

        jLabel3.setText("Duration");

        jLabel4.setText("Rating");

        jLabel5.setText("Status");

        jLabel6.setText("Image");

        durationField.addActionListener(this::durationFieldActionPerformed);

        titleField.addActionListener(this::titleFieldActionPerformed);

        addImagebutton.setText("Add Image");
        addImagebutton.addActionListener(this::addImagebuttonActionPerformed);

        doneButton.setText("Done");
        doneButton.addActionListener(this::doneButtonActionPerformed);

        imageField.addActionListener(this::imageFieldActionPerformed);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHOWING", "UPCOMING", "ARCHIVED", " " }));
        statusComboBox.addActionListener(this::statusComboBoxActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addImagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 118, Short.MAX_VALUE)
                            .addComponent(ratingField)
                            .addComponent(durationField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genreField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ratingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(imagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(addImagebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void updatePreview(String path) {
		if (path == null || path.isEmpty()) return;
		
		try {
			ImageIcon icon = new ImageIcon(path);
			Image img = icon.getImage();
			
			int w = imagePreview.getWidth() > 0 ? imagePreview.getWidth() : 120;
			int h = imagePreview.getHeight() > 0 ? imagePreview.getHeight() : 150;
			
			Image scaledImg = img.getScaledInstance( w, h, Image.SCALE_SMOOTH);
			imagePreview.setIcon(new ImageIcon(scaledImg));
			imagePreview.setText("");
			
		} catch (Exception e) {
			imagePreview.setText("Invalid Image");
			imagePreview.setIcon(null);
		}
	}
	
	
    private void durationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        try {
			String title = titleField.getText().trim();
			String genre = genreField.getText().trim();
			int duration = Integer.parseInt(durationField.getText().trim());
			double rating = Double.parseDouble(ratingField.getText().trim());
			Movie.Status status = Movie.Status.valueOf(statusComboBox.getSelectedItem().toString());
			String imagePath = imageField.getText().trim();
			
			if (title.isEmpty()) { // Check all if empty
				JOptionPane.showMessageDialog(this, "Please fill in all fields");
				return;
			}
			
			String nextID = Movie.generateNextID();
			
			Movie newMovie = new Movie(nextID, title, genre, duration, rating, status, imagePath);
			newMovie.append();
			JOptionPane.showMessageDialog(this, "Movie added successfully");
			if (parent != null) {
				parent.loadMovieTable();
			}
			this.dispose();
			
			
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Duration must be an integer and Rating a dobule.");
		} catch (IllegalArgumentException e) {
			JOptionPane.showMessageDialog(this, "Status must be : SHOWING, UPCOMING or ARCHIVED"); // Not needed
		} catch (ArrayIndexOutOfBoundsException e){
                        JOptionPane.showMessageDialog(this, "No image detected");
                }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void imageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageFieldActionPerformed

    private void addImagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImagebuttonActionPerformed
        JFileChooser chooser = new JFileChooser();
		if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			File sourceFile = chooser.getSelectedFile();
			
			try {
				String fileName = sourceFile.getName();
				Path destPath = Paths.get("data", "assets", "posters", fileName);
				Files.createDirectories(destPath.getParent());
				Files.copy(sourceFile.toPath(), destPath, StandardCopyOption.REPLACE_EXISTING);
				imageField.setText("data/assets/posters/" + fileName);
				updatePreview(sourceFile.getAbsolutePath());
			} catch (Exception e ){
				JOptionPane.showMessageDialog(this, "Failed to copy image: " + e.getMessage());
			}
		}
    }//GEN-LAST:event_addImagebuttonActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new AddMovieUI(null).setVisible(true));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImagebutton;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextField durationField;
    private javax.swing.JTextField genreField;
    private javax.swing.JTextField imageField;
    private javax.swing.JLabel imagePreview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField ratingField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
