/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;

import cinema.models.Showtime;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian
 */
public class AddShowtimeUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddShowtimeUI.class.getName());

    /**
     * Creates new form AddShowtimeUI
     */
    private ManagerUI parent;
    public AddShowtimeUI(ManagerUI parent) {
        this.parent = parent;
        initComponents();
        
        ShowtimeIDField.setText(Showtime.generateNextID());
        ShowtimeIDField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowtimeIDLabel = new javax.swing.JLabel();
        MovieIDLabel1 = new javax.swing.JLabel();
        HallLabel = new javax.swing.JLabel();
        DateTimeLabel = new javax.swing.JLabel();
        SeatsLabel = new javax.swing.JLabel();
        ShowtimeIDField = new javax.swing.JTextField();
        MovieIDField = new javax.swing.JTextField();
        HallField = new javax.swing.JTextField();
        DateTimeField = new javax.swing.JTextField();
        SeatsField = new javax.swing.JTextField();
        ShowtimeDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ShowtimeIDLabel.setText("Showtime ID");

        MovieIDLabel1.setText("Movie ID");

        HallLabel.setText("Hall");

        DateTimeLabel.setText("Date & Time");

        SeatsLabel.setText("Price");

        ShowtimeIDField.addActionListener(this::ShowtimeIDFieldActionPerformed);

        MovieIDField.addActionListener(this::MovieIDFieldActionPerformed);

        HallField.addActionListener(this::HallFieldActionPerformed);

        DateTimeField.addActionListener(this::DateTimeFieldActionPerformed);

        SeatsField.addActionListener(this::SeatsFieldActionPerformed);

        ShowtimeDoneButton.setText("Done");
        ShowtimeDoneButton.addActionListener(this::ShowtimeDoneButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowtimeIDLabel)
                    .addComponent(MovieIDLabel1)
                    .addComponent(HallLabel)
                    .addComponent(DateTimeLabel)
                    .addComponent(SeatsLabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HallField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MovieIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowtimeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowtimeDoneButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowtimeIDLabel)
                    .addComponent(ShowtimeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovieIDLabel1)
                    .addComponent(MovieIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HallLabel)
                    .addComponent(HallField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateTimeLabel)
                    .addComponent(DateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeatsLabel)
                    .addComponent(SeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(ShowtimeDoneButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowtimeIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowtimeIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowtimeIDFieldActionPerformed

    private void MovieIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieIDFieldActionPerformed

    private void HallFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HallFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HallFieldActionPerformed

    private void DateTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTimeFieldActionPerformed

    private void SeatsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsFieldActionPerformed

    private void ShowtimeDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowtimeDoneButtonActionPerformed
        try {
            String ID = ShowtimeIDField.getText().trim();
            String MovieID = MovieIDField.getText().trim();
            int Hall = Integer.parseInt(HallField.getText().trim());
            String DateTime = DateTimeField.getText().trim();
            double Price = Double.parseDouble(SeatsField.getText().trim());     //fix price/seats ASAP
            

            if (MovieID.isEmpty()) { // Check all if empty
                JOptionPane.showMessageDialog(this, "Please fill in all fields");
                return;
            }

            String nextID = Showtime.generateNextID();

            Showtime newShowtime = new Showtime(ID, MovieID, Hall, DateTime, Price);
            newShowtime.append();
            JOptionPane.showMessageDialog(this, "Showtime added successfully");
            if (parent != null) {
                parent.loadShowtimeTable();
            }
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please ensure input is following format.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error has occured");
        }
    }//GEN-LAST:event_ShowtimeDoneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateTimeField;
    private javax.swing.JLabel DateTimeLabel;
    private javax.swing.JTextField HallField;
    private javax.swing.JLabel HallLabel;
    private javax.swing.JTextField MovieIDField;
    private javax.swing.JLabel MovieIDLabel1;
    private javax.swing.JTextField SeatsField;
    private javax.swing.JLabel SeatsLabel;
    private javax.swing.JButton ShowtimeDoneButton;
    private javax.swing.JTextField ShowtimeIDField;
    private javax.swing.JLabel ShowtimeIDLabel;
    // End of variables declaration//GEN-END:variables
}
