/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;

import cinema.models.Booking;
import cinema.models.Movie;
import cinema.models.Seat;
import cinema.models.Showtime;
import cinema.models.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ivan
 */
public class BookingUI extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingUI.class.getName());
	private Showtime showtime;
	private User customer;
	private List<Seat> selectedSeats = new ArrayList<>();
	private JButton[][] seatButtons = new JButton[5][10];
	private final double PRICE_PER_SEAT = 18.00;
	

	/**
	 * Creates new form BookingUI
	 */
	public BookingUI(Showtime showtime, User customer, Movie movie) {
		this.showtime = showtime;
		this.customer = customer;
		initComponents();
		setupSeatMap(); 
		updateSummary();	
		setTitle("Booking : " + movie.getTitle());
		setLocationRelativeTo(null);
	}
	
	private void setupSeatMap() {
		seatPanel.removeAll();
		seatPanel.setLayout(new GridBagLayout());
		JPanel innerGrid = new JPanel(new GridLayout(5, 10, 5, 5));
		String[][] layout = showtime.getSeats();
		
		for (int r = 0; r < 5; r++) {
			for (int c = 0; c < 10; c++) {
				final int row = r;
				final int col = c;
				
				String label = (char)('A' + r) + String.valueOf(c + 1);
				JButton btn = new JButton(label);
				btn.setPreferredSize(new Dimension(60, 60));
				btn.setFont(new Font("SansSerif", Font.PLAIN, 14));
				
				if (layout[r][c].equals("1")) {
					btn.setBackground(new Color(80, 80, 80));
                    btn.setEnabled(false);
                    btn.setText("X");
				} else {
					btn.setBackground(new Color(40, 150, 40));
                    btn.addActionListener(e -> toggleSeat(btn, row, col));
				}
				
				seatButtons[r][c] = btn;
				innerGrid.add(btn);
			}
		}
		seatPanel.add(innerGrid);
		seatPanel.revalidate();
		seatPanel.repaint();
	}
	
	private void toggleSeat(JButton btn, int r, int c) {
		Seat s = new Seat(r, c);
		if (selectedSeats.contains(s)) {
			selectedSeats.remove(s);
			btn.setBackground(new Color(40, 150, 40));
		} else {
			selectedSeats.add(s);
			btn.setBackground(Color.ORANGE);
		}
		updateSummary();
	}
	
	private void updateSummary() {
		double total = selectedSeats.size() * PRICE_PER_SEAT;
		totalLabel.setText(String.format("Total: RM %.2f", total));
	}
	
	private void processCheckout() {
		if (selectedSeats.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please select at least 1 seat");
			return;
		} 

		StringBuilder seatLabels = new StringBuilder();
		for (Seat s : selectedSeats) {
			showtime.bookSeat(s.row(), s.col());
			seatLabels.append((char)('A' + s.row())).append(s.col() + 1).append(";");
		}

		Showtime.update(showtime.getShowtimeID(), showtime);

		double total = selectedSeats.size() * showtime.getPrice();
		String bookingID = Booking.generateNextID();

		Booking newBooking = new Booking(
				bookingID,
				customer.getUserID(),
				showtime.getShowtimeID(),
				seatLabels.toString(),
				total
		);

		newBooking.append();
		JOptionPane.showMessageDialog(this, "Booking Successful!\nBooking ID: " + bookingID);
		this.dispose();
	}
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        totalLabel.setText("Total");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(this::confirmButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(confirmButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        processCheckout();
    }//GEN-LAST:event_confirmButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
