/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;

import cinema.models.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ivana
 */
public class ClerkUI extends CustomerUI {
    

    /**
     * Creates new form ClerkUI
     */
    public ClerkUI(User user) {
        super(user);    // ts makes it so that it reuses the logic from customerUI
        clerkPermission();      //modifies customerUI to have clerk permisisons
        this.revalidate();
        this.repaint();
        setTitle("Clerk Menu: " + user.getName());
    }
    
    private void clerkPermission() {    // overriedes the bookings button from customerUI with all bookings for Clerk
        JPanel main = jPanel1;
        BorderLayout layout = (BorderLayout) main.getLayout();
        Component northComp = layout.getLayoutComponent(BorderLayout.NORTH);
        
        if (northComp instanceof JPanel){
            JPanel header = (JPanel) northComp;
            
            for (Component c : header.getComponents()){
                if (c instanceof JButton && ((JButton) c).getText().equals("My Bookings")){
                    header.remove(c);
                }
            }
        
        
        JButton manageButton = new JButton("Manage All Bookings");
        
        manageButton.addActionListener(e -> {
            new ClerkBookingUI().setVisible(true);
        });
        
        
        header.add(manageButton);
        header.revalidate();
        header.repaint();
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
