/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;

import cinema.models.Booking;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.TableModelEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ivana
 */
public class ClerkBookingUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClerkBookingUI.class.getName());

    /**
     * Creates new form ClerkBookingUI
     */
    public ClerkBookingUI() {
        initComponents();
        loadClerkBookingTable();
        setTitle("Booking List");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public void loadClerkBookingTable(){
        Object[][] clerkData = Booking.get2DArray();
        String[] clerkHeaders = {"ID", "Customer", "Movie", "Seats", "Showtime", "Total"};
        
        DefaultTableModel clerkModel = new DefaultTableModel(clerkData, clerkHeaders){
            @Override
            public boolean isCellEditable(int row, int column){
                return column == 3;
            }
        };
        clerkBookingTable.setModel(clerkModel);
        
        clerkModel.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE){
                updateBooking(e.getFirstRow());
            }
        });
    }
    
    private void updateBooking(int row){
        String id = clerkBookingTable.getValueAt(row, 0).toString();
        String updatedSeats = clerkBookingTable.getValueAt(row, 3).toString();
        
        Booking originalSeats = Booking.getAll().stream()
                .filter(b -> b.getBookingID().equals(id))
                .findFirst().orElse(null);
        
        if (originalSeats != null) {
            Booking updated = new Booking(id, originalSeats.getUserID(),originalSeats.getShowtimeID(), updatedSeats.replace(",", ";"),originalSeats.getTotalAmount());
           Booking.update(id, updated);
            System.out.println("Booking successfully updated");
        }
    }
    
    private void deleteBooking(){
        int row = clerkBookingTable.getSelectedRow();
        if (row != -1){
            String id = clerkBookingTable.getValueAt(row, 0).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Cancel Booking>?", "Confirm cancellation?", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                Booking.delete(id);
                loadClerkBookingTable();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please select a booking to delete");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clerkBookingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clerkBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(clerkBookingTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClerkBookingUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clerkBookingTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
