/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;
import cinema.models.Booking;
import cinema.models.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        

/**
 *
 * @author Isaac
 */
public class CustomerBookingUI extends javax.swing.JFrame {     // simplified view for customers to see only their reservation history  
    
    private User currentUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerBookingUI.class.getName());

    /**
     * Creates new form CustomerBookingUI
     */
    public CustomerBookingUI(User user) {
        initComponents();
        this.currentUser = user;
        setTitle("My Bookings: " + user.getName());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loadBookingTable();
    }
    
    public void loadBookingTable()  {       // this retrieves only the bookings that links with the logged in user
        Object[][] customerBookingData = Booking.get2DArray(currentUser.getUserID());
        String[] customerBookingHeaders = {"Booking ID", "Movie", "Seats", "Date & Time", "Total Paid"};
        
        DefaultTableModel customerBookingModel = new DefaultTableModel(customerBookingData, customerBookingHeaders) {
            @Override
            public boolean isCellEditable(int row, int column)  {
                return false;
            }
        };
        
        customerBookingTable.setModel(customerBookingModel);
    }
    
    private void deleteBooking() {      // this is to cancel bookings
        int selectedRow = customerBookingTable.getSelectedRow();
        
        if (selectedRow != -1){
            String bookingID = customerBookingTable.getValueAt(selectedRow, 0).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?" , "Confirm cancellation?", JOptionPane.YES_NO_OPTION);
           
            if (confirm == JOptionPane.YES_OPTION)  {
                Booking.delete(bookingID);
                loadBookingTable();
                javax.swing.JOptionPane.showMessageDialog(this, "Booking canceled successfully");
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a booking to delete");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerBookingTable = new javax.swing.JTable();
        deleteSelectedCustomerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        customerBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(customerBookingTable);

        deleteSelectedCustomerButton.setText("Delete Selected");
        deleteSelectedCustomerButton.addActionListener(this::deleteSelectedCustomerButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteSelectedCustomerButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSelectedCustomerButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSelectedCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedCustomerButtonActionPerformed
        // TODO add your handling code here:
        deleteBooking();
        
    }//GEN-LAST:event_deleteSelectedCustomerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerBookingTable;
    private javax.swing.JButton deleteSelectedCustomerButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
