/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.ui;
import cinema.models.*;
import cinema.services.MovieManager;
import cinema.services.UserManager;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class ManagerUI extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerUI.class.getName());

	/**
	 * Creates new form ManagerUI
	 */
	public ManagerUI() {
		initComponents();
		loadUserTable();
		loadMovieTable();
		
		userTable.getModel().addTableModelListener(e -> {
			int row = e.getFirstRow();
			int column = e.getColumn();
			
			if (e.getType() == TableModelEvent.UPDATE) {
				updateUserFromTable(row);
			}
		});
			
		movieTable.getModel().addTableModelListener(e -> {
			int row = e.getFirstRow();
			int column = e.getColumn();
			
			if (e.getType() == TableModelEvent.UPDATE) {
				updateMovieFromTable(row);
			}
		});
		
		
		
	}
	
	public void loadUserTable() {
		UserManager um = new UserManager();
		Object[][] userData = um.get2DArray();
		String[] userHeaders = {"ID", "Name", "Email", "Password", "Role"};
 		DefaultTableModel userModel = new DefaultTableModel(userData, userHeaders) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return column != 0; 
			}
		};
		userTable.setModel(userModel);
	}
	
	public void loadMovieTable() {
		MovieManager mm = new MovieManager();
		Object[][] movieData = mm.get2DArray();
		String[] movieHeaders = {"ID", "Title", "Genre", "Duration ( Minutes )", "Rating", "Status", "Poster Path"};
		DefaultTableModel movieModel = new DefaultTableModel(movieData, movieHeaders) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return column != 0;
			}
		};
		movieTable.setModel(movieModel);
	}
	
	private void updateUserFromTable(int row) {
		DefaultTableModel model = (DefaultTableModel) userTable.getModel();
		
		String ID = model.getValueAt(row, 0).toString();
		String NAME = model.getValueAt(row, 1).toString();
		String EMAIL = model.getValueAt(row, 2).toString();
		String PASSWORD = model.getValueAt(row, 3).toString();
		String ROLESTR = model.getValueAt(row, 4).toString(); // TODO : Add validation here.

		Role ROLE = Role.valueOf(ROLESTR.toUpperCase());
		
		User updatedUser;
		
		if (ROLE == Role.CUSTOMER) {
			updatedUser = new Customer(ID, NAME, EMAIL, PASSWORD);
		} else if (ROLE == Role.CLERK) {
			updatedUser = new Clerk(ID, NAME, EMAIL, PASSWORD);
		} else {
			updatedUser = new Manager(ID, NAME, EMAIL, PASSWORD);
		}
		
		UserManager um = new UserManager();
		um.update(ID, updatedUser);
		
		System.out.println("User " + ID + " updated in text file.");
	}
	
	private void updateMovieFromTable(int row) {
		DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
		
		String ID = model.getValueAt(row, 0).toString();
		String TITLE = model.getValueAt(row, 1).toString();
		String GENRE = model.getValueAt(row, 2).toString();
		int DURATION = Integer.parseInt(model.getValueAt(row, 3).toString()); // autistic code my god - Ivan
		double RATING = Double.parseDouble(model.getValueAt(row, 4).toString()); // TODO : DEFINITELY ADD VALIDATION HERE. FUTURE IVAN PLS FIX
		Status STATUS = Status.valueOf(model.getValueAt(row, 5).toString());
		
		
		String POSTERPATH = model.getValueAt(row, 6).toString();
		
		MovieManager mm = new MovieManager();
		Movie updatedMovie = new Movie(ID, TITLE, GENRE, DURATION, RATING, STATUS, POSTERPATH);
		mm.update(ID, updatedMovie); // Takes in ID and Movie object, replaces the corresponding ID the object.
		
		System.out.println("Movie " + ID + " updated in text file.");
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        deleteSelectedUserButton = new javax.swing.JButton();
        addNewUserButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        addNewMovieButton = new javax.swing.JButton();
        deleteSelectedMoiveButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        deleteSelectedUserButton.setText("Delete Selected");
        deleteSelectedUserButton.addActionListener(this::deleteSelectedUserButtonActionPerformed);

        addNewUserButton.setText("Add New");
        addNewUserButton.addActionListener(this::addNewUserButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(deleteSelectedUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteSelectedUserButton)
                    .addComponent(addNewUserButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Users", jPanel1);

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(movieTable);

        addNewMovieButton.setText("Add New");
        addNewMovieButton.addActionListener(this::addNewMovieButtonActionPerformed);

        deleteSelectedMoiveButton.setText("Delete Selected");
        deleteSelectedMoiveButton.addActionListener(this::deleteSelectedMoiveButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(deleteSelectedMoiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteSelectedMoiveButton)
                    .addComponent(addNewMovieButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Movies", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Bookings", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void deleteMovie() {
		int selectedRow = movieTable.getSelectedRow();
		if (selectedRow != -1) {
			String ID = movieTable.getValueAt(selectedRow, 0).toString();
			int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
			
			if (confirm == JOptionPane.YES_OPTION) {
				new MovieManager().delete(ID); // Delete from file.
				loadMovieTable(); // Reload list.
			}
		} else {
			JOptionPane.showMessageDialog(this, "Please select a movie to delete");
		}
	}
	
	private void deleteUser() {
		int selectedRow = userTable.getSelectedRow();
		if (selectedRow != -1) {
			String ID = userTable.getValueAt(selectedRow, 0).toString();
			int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
			
			if (confirm == JOptionPane.YES_OPTION) {
				new UserManager().delete(ID); // Delete from file.
				loadUserTable(); // Reload list.
			}
		} else {
			JOptionPane.showMessageDialog(this, "Please select a user to delete");
		}
	}
	
	
	
    private void deleteSelectedMoiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedMoiveButtonActionPerformed
		deleteMovie();
    }//GEN-LAST:event_deleteSelectedMoiveButtonActionPerformed

    private void addNewMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMovieButtonActionPerformed
        AddMovieUI ui = new AddMovieUI(this);
		ui.setVisible(true);
		ui.setLocationRelativeTo(null);
    }//GEN-LAST:event_addNewMovieButtonActionPerformed

    private void deleteSelectedUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedUserButtonActionPerformed
        deleteUser();
    }//GEN-LAST:event_deleteSelectedUserButtonActionPerformed

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewUserButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new ManagerUI().setVisible(true));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewMovieButton;
    private javax.swing.JButton addNewUserButton;
    private javax.swing.JButton deleteSelectedMoiveButton;
    private javax.swing.JButton deleteSelectedUserButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable movieTable;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
